### ISSUE TITLE
Projects 2017

### ISSUE THREAD

**Issue by JohanMabille** [QuantStack/cpp_dauphine#17]
The projects descriptions are available:

[breakeven-volatility](https://github.com/QuantStack/cpp_dauphine/blob/master/projects/breakeven-volatility/breakeven-volatility.pdf)
[currency ranking](https://github.com/QuantStack/cpp_dauphine/blob/master/projects/currency-ranking/currency-ranking.pdf)
[super replication](https://github.com/QuantStack/cpp_dauphine/blob/master/projects/super-replication/bundle.pdf)

We'd like you to choose a project and a team mate before next Thursday and reply here with your choices.
Also, even if there is still a lot of features of C++ that have not been taught yet, you should start thinking about the project and how you would do things. 

@Arthurim @bodinierthomas @marcellomak @MaximeBo @maximelefebvre @MoonBiz @olpig @RemiPeyrot @siou0107 @SJD1882 @Soumirai @thofour @Yingl

**Comment by JohanMabille** [comment]
Some of you still have problems with the installation of the tools, please come and open an issue here or ask for help on the [gitter channel](https://gitter.im/QuantStack/cpp_dauphine). We're available for help.

Also if you still have problem understanding git, come on the [gitter channel](https://gitter.im/QuantStack/cpp_dauphine) and ask, we can explain things that are not clear (and even do video calls if this is faster than typing).

**Comment by Arthurim** [comment]
I will be working on the Breakeven vol project alone. -Arthur

**Comment by marcellomak** [comment]
Hello Johan,

Maxime Bouin and I, Marcello Mak will be doing the "Breakeven-Volatility"
project.
Thank you so much and see you very soon!

Best regards,
Marcello

**Comment by siou0107** [comment]
Hi,

Maxime Lefebvre and I, Louis le Pas de Sécheval, will also be doing the "Breakeven-Volatility" project.

**Comment by SJD1882** [comment]
Hi,

Julien Leroy, Thomas Fourcroy and I, Sébastien David, will be doing the "Currency Ranking" project.

**Comment by Soumirai** [comment]
Hello,
Ruiying and I will work on the "Breakeven-Volatility" project.
Nicolas
